package co.edu.poli.cnt.simulador.vista;

import javax.swing.SwingUtilities;

/**
 *
 * @author Antonio Paternina <acpaternina@poli.edu.co>
 */
public class PanelBienvenida extends javax.swing.JPanel {

    /**
     * Creates new form PanelBienvenida
     */
    public PanelBienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloPrincipalLabel = new javax.swing.JLabel();
        botonComenzarPanel = new javax.swing.JPanel();
        glueHorizontalAntes = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        botonComenzar = new javax.swing.JButton();
        GlueHorizontalDespues = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setPreferredSize(new java.awt.Dimension(1280, 800));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        tituloPrincipalLabel.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        tituloPrincipalLabel.setText("<html><p style=\"center\">Simulador Examen de Certificación</p></html>");
        tituloPrincipalLabel.setMinimumSize(new java.awt.Dimension(1000, 100));
        jPanel1.add(tituloPrincipalLabel);

        botonComenzarPanel.setLayout(new javax.swing.BoxLayout(botonComenzarPanel, javax.swing.BoxLayout.LINE_AXIS));
        botonComenzarPanel.add(glueHorizontalAntes);

        botonComenzar.setText("Comenzar");
        botonComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComenzarActionPerformed(evt);
            }
        });
        botonComenzarPanel.add(botonComenzar);
        botonComenzarPanel.add(GlueHorizontalDespues);

        jPanel1.add(botonComenzarPanel);

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void botonComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComenzarActionPerformed
        // mostrar panel del examen
        VistaPrincipal vistaPrincipal = (VistaPrincipal) SwingUtilities.getWindowAncestor(this);
        vistaPrincipal.mostrarPanelExamen();
    }//GEN-LAST:event_botonComenzarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler GlueHorizontalDespues;
    private javax.swing.JButton botonComenzar;
    private javax.swing.JPanel botonComenzarPanel;
    private javax.swing.Box.Filler glueHorizontalAntes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloPrincipalLabel;
    // End of variables declaration//GEN-END:variables
}
