package co.edu.poli.cnt.simulador.vista;

import co.edu.poli.cnt.simulador.modelo.PreguntaEntity;
import co.edu.poli.cnt.simulador.repositorio.PreguntaRepositorio;
import co.edu.poli.cnt.simulador.repositorio.PreguntaRepositorioImpl;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import org.apache.log4j.Logger;

/**
 *
 * @author Antonio Paternina <acpaternina@poli.edu.co>
 */
public class PanelExamen extends JPanel {
    
    private static final Logger LOGGER = Logger.getLogger(PanelExamen.class.getName());

    private PreguntaRepositorio preguntaRepositorio;

    /**
     * Creates new form PanelExamen
     */
    public PanelExamen() {
        JPanel estePanel = this;
        initComponents();
        preguntaRepositorio = PreguntaRepositorioImpl.getInstancia();        

        // cargar las preguntas del examen
        final List<PreguntaEntity> preguntas = preguntaRepositorio.getAllPreguntaEntity();
        LOGGER.info(preguntas);
        listaPreguntas.setModel(new AbstractListModel<PreguntaEntity>() {
            @Override
            public int getSize() {
                return preguntas.size();
            }

            @Override
            public PreguntaEntity getElementAt(int index) {
                return preguntas.get(index);
            }
        });
        listaPreguntas.setCellRenderer(new ListaPreguntaCellRenderer());
        listaPreguntas.setLayoutOrientation(JList.HORIZONTAL_WRAP);
        listaPreguntas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // iniciar el temporizador
        this.temporizador.inicializar(60 * 120 - 1, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // mostrar panel de resultado
                VistaPrincipal vistaPrincipal = (VistaPrincipal) SwingUtilities.getWindowAncestor(estePanel);
                vistaPrincipal.mostrarPanelResultado();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEncabezado = new javax.swing.JPanel();
        temporizador = new co.edu.poli.cnt.simulador.vista.Temporizador();
        panelNavegadorDePreguntas = new javax.swing.JPanel();
        scrollPaneListaPreguntas = new javax.swing.JScrollPane();
        listaPreguntas = new javax.swing.JList<>();
        panelControles = new javax.swing.JPanel();
        botonSiguiente = new javax.swing.JButton();
        botonAnterior = new javax.swing.JButton();
        checkMarcar = new javax.swing.JCheckBox();
        panelPregunta = new javax.swing.JPanel();
        scrollAreaPregunta = new javax.swing.JScrollPane();

        setPreferredSize(new java.awt.Dimension(1280, 800));

        panelEncabezado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(temporizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(temporizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        panelNavegadorDePreguntas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listaPreguntas.setModel(new javax.swing.AbstractListModel<PreguntaEntity>() {
            public int getSize() { return 0; }
            public PreguntaEntity getElementAt(int i) { return null; }
        });
        listaPreguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPreguntasMouseClicked(evt);
            }
        });
        listaPreguntas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPreguntasValueChanged(evt);
            }
        });
        scrollPaneListaPreguntas.setViewportView(listaPreguntas);

        javax.swing.GroupLayout panelNavegadorDePreguntasLayout = new javax.swing.GroupLayout(panelNavegadorDePreguntas);
        panelNavegadorDePreguntas.setLayout(panelNavegadorDePreguntasLayout);
        panelNavegadorDePreguntasLayout.setHorizontalGroup(
            panelNavegadorDePreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavegadorDePreguntasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneListaPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelNavegadorDePreguntasLayout.setVerticalGroup(
            panelNavegadorDePreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavegadorDePreguntasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneListaPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelControles.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonSiguiente.setText("next");

        botonAnterior.setText("previous");

        checkMarcar.setText("mark");
        checkMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMarcarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControlesLayout = new javax.swing.GroupLayout(panelControles);
        panelControles.setLayout(panelControlesLayout);
        panelControlesLayout.setHorizontalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControlesLayout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(checkMarcar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSiguiente)
                .addContainerGap())
        );

        panelControlesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonAnterior, botonSiguiente});

        panelControlesLayout.setVerticalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlesLayout.createSequentialGroup()
                .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSiguiente)
                    .addComponent(botonAnterior)
                    .addComponent(checkMarcar))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        panelPregunta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelPreguntaLayout = new javax.swing.GroupLayout(panelPregunta);
        panelPregunta.setLayout(panelPreguntaLayout);
        panelPreguntaLayout.setHorizontalGroup(
            panelPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollAreaPregunta)
                .addContainerGap())
        );
        panelPreguntaLayout.setVerticalGroup(
            panelPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollAreaPregunta)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelNavegadorDePreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNavegadorDePreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMarcarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMarcarActionPerformed

    private void listaPreguntasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPreguntasValueChanged
        if(!evt.getValueIsAdjusting()) {
            JList<PreguntaEntity> lista = (JList<PreguntaEntity>) evt.getSource();
            lista.repaint();
        }
    }//GEN-LAST:event_listaPreguntasValueChanged

    private void listaPreguntasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPreguntasMouseClicked
        JList list = (JList<PreguntaEntity>) evt.getComponent();
        PreguntaEntity pregunta = (PreguntaEntity) list.getSelectedValue();
        System.out.println(pregunta);
    }//GEN-LAST:event_listaPreguntasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnterior;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JCheckBox checkMarcar;
    private javax.swing.JList<PreguntaEntity> listaPreguntas;
    private javax.swing.JPanel panelControles;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelNavegadorDePreguntas;
    private javax.swing.JPanel panelPregunta;
    private javax.swing.JScrollPane scrollAreaPregunta;
    private javax.swing.JScrollPane scrollPaneListaPreguntas;
    private co.edu.poli.cnt.simulador.vista.Temporizador temporizador;
    // End of variables declaration//GEN-END:variables

}
